Repository boostcampwm-2021/web15-TadakTadak, pull requests merged in 2021-12, with the labels that each got.

#273 테스트 코드 작성
  server/api/src/builder/auth/join-request.dto.builder.ts
  server/api/src/builder/auth/login-request.dto.builder.ts
  server/api/src/builder/index.ts
  server/api/src/builder/user/user-response.dto.builder.ts
  server/api/src/builder/user/user-update.dto.builder.ts
  server/api/src/domain/auth/dto/login-request.dto.ts
  server/api/src/domain/auth/dto/user-response.dto.ts
  server/api/src/domain/auth/service/auth.service.spec.ts
  server/api/src/domain/auth/service/auth.service.ts
  server/api/src/domain/auth/strategy/jwt.strategy.ts
  server/api/src/domain/user/dto/user-update.dto.ts
  server/api/src/domain/user/repository/user.repository.ts
  server/api/src/domain/user/service/user.service.spec.ts
  server/api/src/domain/user/service/user.service.ts
Labels: 🎯 백엔드

#276 API 테스트 코드 작성
  client/src/__test__/apis.test.ts
  client/src/__test__/utils.test.ts
  client/src/utils/utils.ts
Labels: 리팩토링

#277 몇가지 유틸함수에 대한 테스트코드 작성, 사용하지 않는 파일 제거
  client/package-lock.json
  client/package.json
  client/src/components/ServiceInfo/index.tsx
  client/src/components/ServiceInfo/style.ts
  client/src/components/room/RoomCard/index.tsx
  client/src/utils/cookie.ts
  client/src/utils/utils.test.ts
  client/src/utils/utils.ts
  client/yarn.lock
Labels: 리팩토링

#287 강퇴 시 소켓이 끊기는 버그 개선, 토스트메시지 수정
  client/src/components/campfire/CamperList/index.tsx
  client/src/components/form/Join/index.tsx
  client/src/components/form/MakeRoom/index.tsx
  client/src/components/sideBar/Room/index.tsx
  client/src/components/sideBar/SideBar/style.ts
  client/src/components/sideBar/chat/ChatList/style.ts
  client/src/utils/constant.ts
  client/src/utils/styleConstant.ts
  client/src/utils/utils.test.ts
  client/src/utils/utils.ts
Labels: 버그, 리팩토링

#289 Fix: 참가자 탭 상태 문제 수정
  client/src/components/sideBar/Room/index.tsx
Labels: 버그

#294 Fix: 호스트의 방 삭제 로직버그 수정, 방 내부 새로고침 대응 외 2개
  client/src/components/campfire/Controller/index.tsx
  client/src/components/sideBar/Room/index.tsx
  client/src/components/video/VideoController/index.tsx
  client/src/pages/Campfire/Campfire.tsx
  client/src/pages/Tadak/Tadak.tsx
  client/src/socket/socket.ts
  client/src/utils/utils.ts
  server/socket/src/gateway/room.service.ts
Labels: 버그, 리팩토링

#304 방 인원 카운트방식 변경, 화면공유 버그 해결, 화면공유시에만 전체화면으로 변경
  client/src/components/room/RoomCard/style.ts
  client/src/components/video/Screenshare/index.tsx
  client/src/components/video/VideoCard/index.tsx
  client/src/components/video/VideoController/index.tsx
  client/src/components/video/config.ts
  client/src/pages/Campfire/Campfire.tsx
  client/src/pages/Tadak/Tadak.tsx
  client/src/utils/constant.ts
Labels: 버그, 리팩토링
