Repository boostcampwm-2021/web15-TadakTadak, pull requests merged in 2021-11, with the labels that each got.

#20 개발 환경 설정 - #6
  .gitmessage
  client/.gitignore
  client/README.md
  client/package-lock.json
  client/package.json
  client/public/index.html
  client/src/App.tsx
  client/src/assets/tmp.txt
  client/src/components/tmp.txt
  client/src/contexts/tmp.txt
  client/src/index.tsx
  client/src/pages/tmp.txt
  client/src/styles/tmp.txt
  client/src/utils/tmp.txt
  client/tsconfig.json
  client/yarn.lock
Labels: ⚙️ 기능/기획, 🎯 프론트엔드

#19 개발 환경 설정 - #6
  .github/ISSUE_TEMPLATE/issue-template.md
  .gitignore
  server/.eslintrc.js
  server/.gitignore
  server/.prettierrc
  server/README.md
  server/nest-cli.json
  server/package-lock.json
  server/package.json
  server/src/app.controller.spec.ts
  server/src/app.controller.ts
  server/src/app.module.ts
  server/src/app.service.ts
  server/src/auth/auth.controller.spec.ts
  server/src/auth/auth.controller.ts
  server/src/auth/auth.module.ts
  server/src/auth/auth.service.spec.ts
  server/src/auth/auth.service.ts
  server/src/main.ts
  server/src/room/room.controller.spec.ts
  server/src/room/room.controller.ts
  server/src/room/room.module.ts
  server/src/room/room.service.spec.ts
  server/src/room/room.service.ts
  server/src/user/user.controller.spec.ts
  server/src/user/user.controller.ts
  server/src/user/user.module.ts
  server/src/user/user.service.spec.ts
  server/src/user/user.service.ts
  server/test/app.e2e-spec.ts
  server/test/jest-e2e.json
  server/tsconfig.build.json
  server/tsconfig.json
Labels: ⚙️ 기능/기획, 🎯 백엔드

#81 개발 환경 설정 - #6
  client/.eslintrc.js
  client/.prettierrc
  client/package-lock.json
  client/package.json
  client/src/index.tsx
  client/yarn.lock
Labels: ⚙️ 기능/기획, 🎯 프론트엔드

#80 개발 환경 설정 - #6
  server/.eslintrc.js
  server/.prettierrc
  server/package-lock.json
  server/src/auth/auth.module.ts
  server/src/room/room.module.ts
  server/src/user/user.controller.ts
  server/src/user/user.module.ts
  server/src/user/user.service.ts
Labels: ⚙️ 기능/기획, 🎯 백엔드

#82 개발 환경 설정 - #6
  client/.eslintrc.js
  client/package-lock.json
  client/src/react-app-env.d.ts
  client/yarn.lock
  package-lock.json
  server/package-lock.json
Labels: ⚙️ 기능/기획, 🎯 프론트엔드, 🎯 백엔드

#83 개발 환경 설정 - #6
  client/.eslintrc.js
  server/.eslintrc.js
Labels: ⚙️ 기능/기획, 🎯 프론트엔드, 🎯 백엔드

#115 로그인 화면, 전역 스타일 설정 - #45
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/pages/Login/Login.tsx
  client/src/pages/Login/index.ts
  client/src/styles/GlobalStyles.ts
  client/src/styles/theme.ts
  client/yarn.lock
  package-lock.json
Labels: 🎯 프론트엔드, 🔑 로그인

#143 Chore: bcrypt 패키지 적용
  server/.prettierrc
  server/package-lock.json
  server/package.json
Labels: 🎯 백엔드

#148 WebRTC를 이용한 다중 사용자 영상, 음성 on/off 기능 & 나가기 기능 구현
  client/.gitignore
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/pages/Main/ChannelForm.tsx
  client/src/pages/Main/DefaultScreen.tsx
  client/src/pages/Main/Main.tsx
  client/src/pages/Main/VideoContainer.tsx
  client/src/pages/Main/VideoController.tsx
  client/src/pages/Main/Videos.tsx
  client/src/pages/Main/index.ts
  client/src/pages/Main/style.ts
  client/src/pages/Main/videoConfig.ts
  client/src/pages/tmp.txt
  client/tsconfig.json
  client/yarn.lock
Labels: 🎯 프론트엔드, 🔴 Must, 📄 타닥타닥, 📄 메인

#146 도커 설치 쉘 스크립트 작성 & FE CI/CD 구성 & BE CI 구성
  .github/workflows/BE-CI.yml
  .github/workflows/FE-CI&CD.yml
  .github/workflows/FE-CI.yml
  client/package.json
  script/install_docker.sh
  script/setting_all.sh
  server/package.json
Labels: 🎯 프론트엔드, 🎯 백엔드, 🔴 Must, 🛒 데브옵스

#149 jwt access token 발급, 회원가입 기능 - #48, #58
  server/package-lock.json
  server/package.json
  server/src/app.controller.spec.ts
  server/src/app.controller.ts
  server/src/app.service.ts
  server/src/auth/auth.module.ts
  server/src/auth/auth.repository.ts
  server/src/auth/controller/auth.controller.ts
  server/src/auth/dto/join-request.dto.ts
  server/src/auth/dto/login-request.dto.ts
  server/src/auth/guard/local-auth.guard.ts
  server/src/auth/service/auth.service.ts
  server/src/auth/strategy/local.strategy.ts
  server/src/utils/bcrypt.ts
Labels: 🎯 백엔드, 🔑 로그인, 🔑 회원가입

#147 로그인,회원가입 폼, 모달 생성 - #45, #56
  client/src/components/JoinForm.tsx
  client/src/components/LoginForm.tsx
  client/src/components/Modal.tsx
  client/src/hooks/useInput.tsx
  client/src/pages/Login/Login.tsx
  client/src/styles/GlobalStyles.ts
  client/src/styles/styled.d.ts
  client/src/styles/theme.ts
Labels: 🎯 프론트엔드, 🔑 로그인, 🔑 회원가입

#150 캠 관련 작업, 메인화면 레이아웃
  client/src/assets/default-avatar.jpeg
  client/src/components/RoomBox.tsx
  client/src/components/VideoBox.tsx
  client/src/pages/Main/ChannelForm.tsx
  client/src/pages/Main/DefaultScreen.tsx
  client/src/pages/Main/Main.tsx
  client/src/pages/Main/Videos.tsx
  client/src/pages/Main/style.ts
  client/src/styles/GlobalStyles.ts
  client/src/styles/theme.ts
  client/yarn.lock
Labels: 🎯 프론트엔드, 📄 타닥타닥, 📄 메인

#151 캠 관련 버튼 UI 구현
  client/package-lock.json
  client/src/components/Button.tsx
  client/src/pages/Main/VideoContainer.tsx
  client/src/pages/Main/VideoController.tsx
  client/src/styles/styled.d.ts
  client/src/styles/theme.ts
  client/yarn.lock
Labels: 🎯 프론트엔드, 🟡 Should, 📄 메인

#155 메인 사이드바, 소개 페이지 추가
  client/src/App.tsx
  client/src/components/LoginModal.tsx
  client/src/components/Modal.tsx
  client/src/components/SideBar.tsx
  client/src/pages/Introduction/Introduction.tsx
  client/src/pages/Introduction/index.ts
  client/src/pages/Login/Login.tsx
  client/src/pages/Login/index.ts
  client/src/pages/Main/Main.tsx
  client/src/pages/Main/style.ts
Labels: 🎯 프론트엔드, 📄 소개, 📄 메인 사이드바

#152 jwt 인증 처리 기능 추가 - #48
  server/package-lock.json
  server/package.json
  server/src/auth/auth.module.ts
  server/src/auth/controller/auth.controller.ts
  server/src/auth/guard/jwt-auth-guard.ts
  server/src/auth/service/auth.service.ts
  server/src/auth/strategy/jwt.strategy.ts
  server/src/main.ts
Labels: 🎯 백엔드, 🔑 로그인

#158 CI 스크립트 변경 & ENV 처리 & 엔티티 작성 & 기본 API 구조 적용
  .github/workflows/BE-CI.yml
  .github/workflows/FE-CI&CD.yml
  .github/workflows/FE-CI.yml
  .gitignore
  server/package-lock.json
  server/package.json
  server/src/auth/auth.repository.ts
  server/src/auth/controller/auth.controller.ts
  server/src/auth/service/auth.service.ts
  server/src/config/typeorm.config.ts
  server/src/main.ts
  server/src/paginate/index.ts
  server/src/paginate/pagination.options.ts
  server/src/paginate/pagination.result.ts
  server/src/paginate/pagination.ts
  server/src/room/controller/room.controller.ts
  server/src/room/room.entity.ts
  server/src/room/room.module.ts
  server/src/room/service/room.service.ts
  server/src/user/controller/user.controller.ts
  server/src/user/dev-field.entity.ts
  server/src/user/follow.entity.ts
  server/src/user/history.entity.ts
  server/src/user/user.entity.ts
Labels: 🎯 백엔드, 🔴 Must, 🛒 데브옵스

#159 Path Alias 추가, 소개페이지 버튼 수정
  client/craco.config.js
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/components/JoinForm.tsx
  client/src/components/LoginForm.tsx
  client/src/components/VideoBox.tsx
  client/src/pages/Introduction/Introduction.tsx
  client/src/pages/Main/Main.tsx
  client/src/pages/Main/VideoController.tsx
  client/src/pages/Main/Videos.tsx
  client/src/styles/styled.d.ts
  client/src/utils/utils.ts
  client/tsconfig.json
  client/tsconfig.paths.json
  client/yarn.lock
Labels: 🎯 프론트엔드

#163 Main Page 라우팅 방식 변경 && 방 생성 Modal 구현
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/components/ListGenerator.tsx
  client/src/components/RoomBox.tsx
  client/src/components/SideBar.tsx
  client/src/hooks/useInput.tsx
  client/src/pages/Main/CreateForm.tsx
  client/src/pages/Main/Main.tsx
  client/src/pages/Main/SideBar.tsx
  client/src/pages/Main/style.ts
  client/src/pages/Room/Room.tsx
  client/src/pages/Room/VideoController.tsx
  client/src/pages/Room/Videos.tsx
  client/src/pages/Room/index.ts
  client/src/pages/Room/videoConfig.ts
  client/yarn.lock
Labels: 🎯 프론트엔드, 🔴 Must, 📄 메인 사이드바, 📄 타닥타닥, 📄 메인

#161 회원가입, 로그인 기능, 유저컨텍스트 추가, 새로고침 시 토큰기반 로그인 유지
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/components/JoinForm.tsx
  client/src/components/LoginForm.tsx
  client/src/components/LoginModal.tsx
  client/src/contexts/userContext.tsx
  client/src/index.tsx
  client/src/pages/Introduction/Introduction.tsx
  client/src/pages/Main/SideBar.tsx
  client/src/pages/Main/style.ts
  client/src/utils/apis.ts
  client/src/utils/cookie.ts
  client/yarn.lock
Labels: 🎯 프론트엔드, 🔑 로그인, 🔑 회원가입

#164 BE 구조 리펙토링 & Transformer & Room 생성 API
  server/package-lock.json
  server/package.json
  server/src/app.module.ts
  server/src/domain/BaseTimeEntity.ts
  server/src/domain/auth/auth.module.ts
  server/src/domain/auth/auth.repository.ts
  server/src/domain/auth/controller/auth.controller.spec.ts
  server/src/domain/auth/controller/auth.controller.ts
  server/src/domain/auth/dto/join-request.dto.ts
  server/src/domain/auth/dto/login-request.dto.ts
  server/src/domain/auth/guard/jwt-auth-guard.ts
  server/src/domain/auth/guard/local-auth.guard.ts
  server/src/domain/auth/service/auth.service.spec.ts
  server/src/domain/auth/service/auth.service.ts
  server/src/domain/auth/strategy/jwt.strategy.ts
  server/src/domain/auth/strategy/local.strategy.ts
  server/src/domain/room/controller/room.controller.spec.ts
  server/src/domain/room/controller/room.controller.ts
  server/src/domain/room/dto/create-room-request.dto.ts
  server/src/domain/room/dto/create-room-response.dto.ts
  server/src/domain/room/repository/room.repository.ts
  server/src/domain/room/room.entity.ts
  server/src/domain/room/room.module.ts
  server/src/domain/room/service/room.service.spec.ts
  server/src/domain/room/service/room.service.ts
  server/src/domain/user/controller/user.controller.spec.ts
  server/src/domain/user/controller/user.controller.ts
  server/src/domain/user/dev-field.entity.ts
  server/src/domain/user/follow.entity.ts
  server/src/domain/user/history.entity.ts
  server/src/domain/user/repository/user.repository.ts
  server/src/domain/user/service/user.service.spec.ts
  server/src/domain/user/service/user.service.ts
  server/src/domain/user/user.entity.ts
  server/src/domain/user/user.module.ts
  server/src/room/controller/room.controller.ts
  server/src/room/room.entity.ts
  server/src/room/service/room.service.ts
  server/src/transformer/BigintValueTransformer.ts
  server/src/transformer/LocalDateTimeTransformer.ts
  server/src/transformer/LocalDateTransformer.ts
  server/src/utils/DateTimeUtil.ts
Labels: 🎯 백엔드, 🔴 Must, 📄 캠프파이어, 📄 타닥타닥, 📄 코딩 라이브

#169 Current User 조회, S3 연동 및 이미지 처리
  server/package-lock.json
  server/package.json
  server/src/domain/auth/controller/auth.controller.ts
  server/src/domain/auth/dto/user-response.dto.ts
  server/src/domain/auth/service/auth.service.ts
  server/src/domain/image/image.module.ts
  server/src/domain/image/service/image.service.ts
  server/src/domain/user/controller/user.controller.ts
  server/src/domain/user/service/user.service.ts
  server/src/domain/user/user.entity.ts
  server/src/domain/user/user.module.ts
Labels: 🎯 백엔드, 🔴 Must, 🔵 Could, 📄 사용자 정보

#168 방 생성 관련 전체적인 리팩토링
  client/src/components/RoomBox.tsx
  client/src/components/main/CreateForm.tsx
  client/src/components/main/SideBar.tsx
  client/src/components/room/tadaktadak/VideoController.tsx
  client/src/components/room/tadaktadak/Videos.tsx
  client/src/components/room/tadaktadak/videoConfig.ts
  client/src/contexts/userContext.tsx
  client/src/pages/Main/Main.tsx
  client/src/pages/Main/SideBar.tsx
  client/src/pages/Main/style.ts
  client/src/pages/Room/Room.tsx
  client/src/utils/apis.ts
Labels: 🎯 프론트엔드, 📄 메인 사이드바, 📄 타닥타닥, 📄 메인

#170 Room 관련 API & Swagger 설정 & Common Exception & Builder 패턴 적용
  server/package-lock.json
  server/package.json
  server/src/builder/builder.ts
  server/src/builder/index.ts
  server/src/builder/room.builder.ts
  server/src/builder/user.builder.ts
  server/src/config/swagger.config.ts
  server/src/config/typeorm.config.ts
  server/src/domain/BaseTimeEntity.ts
  server/src/domain/auth/service/auth.service.ts
  server/src/domain/room/controller/room.controller.ts
  server/src/domain/room/dto/create-room-response.dto.ts
  server/src/domain/room/repository/room.repository.ts
  server/src/domain/room/room.docs.ts
  server/src/domain/room/room.entity.ts
  server/src/domain/room/service/room.service.ts
  server/src/domain/user/repository/user.repository.ts
  server/src/exception/room.exception.ts
  server/src/exception/user.exception.ts
  server/src/filter/http-exception.filter.ts
  server/src/main.ts
Labels: 🎯 백엔드, 🔴 Must, 📄 캠프파이어, 📄 타닥타닥, 📄 메인, 📄 코딩 라이브

#173 방 입장 후 필요 기능(캠과 오디오 끄고 입장, 화면 공유, 음성 인터렉션) 구현
  client/src/components/VideoBox.tsx
  client/src/components/room/tadaktadak/ScreenShareDiv.tsx
  client/src/components/room/tadaktadak/VideoController.tsx
  client/src/components/room/tadaktadak/Videos.tsx
  client/src/pages/Room/Room.tsx
Labels: 🎯 프론트엔드, 📄 타닥타닥

#172 사용자 정보 API 작업 완!
  server/src/builder/user.builder.ts
  server/src/domain/auth/auth.module.ts
  server/src/domain/auth/auth.repository.ts
  server/src/domain/auth/controller/auth.controller.ts
  server/src/domain/auth/dto/user-response.dto.ts
  server/src/domain/auth/service/auth.service.ts
  server/src/domain/auth/strategy/jwt.strategy.ts
  server/src/domain/history/history.entity.ts
  server/src/domain/history/history.module.ts
  server/src/domain/history/repository/history.repository.ts
  server/src/domain/image/service/image.service.ts
  server/src/domain/room/controller/room.controller.ts
  server/src/domain/room/repository/room.repository.ts
  server/src/domain/room/room.entity.ts
  server/src/domain/room/room.module.ts
  server/src/domain/room/service/room.service.ts
  server/src/domain/user/controller/user.controller.ts
  server/src/domain/user/service/user.service.ts
  server/src/domain/user/user.entity.ts
  server/src/domain/user/user.module.ts
  server/src/exception/dev-field.exception.ts
  server/src/exception/index.ts
  server/src/main.ts
Labels: 🎯 백엔드, 📄 사용자 정보

#174 메인화면에서 방 리스트 조회 및 입장 기능
  client/package.json
  client/src/components/LoginForm.tsx
  client/src/components/VideoBox.tsx
  client/src/components/main/CreateForm.tsx
  client/src/components/main/SideBar.tsx
  client/src/components/room/tadaktadak/videoConfig.ts
  client/src/pages/Main/Main.tsx
  client/src/pages/Room/Room.tsx
  client/src/utils/apis.ts
Labels: 🎯 프론트엔드, 📄 메인 사이드바, 📄 메인

#178 배포 전 일부 디자인 수정 및 개선
  client/src/components/Modal.tsx
  client/src/components/RoomBox.tsx
  client/src/components/main/CreateForm.tsx
  client/src/components/main/SideBar.tsx
Labels: 🎯 프론트엔드

#182 로그인 이력 API 완!
  server/package-lock.json
  server/package.json
  server/src/app.module.ts
  server/src/builder/history.builder.ts
  server/src/domain/auth/auth.module.ts
  server/src/domain/auth/auth.repository.ts
  server/src/domain/auth/controller/auth.controller.ts
  server/src/domain/auth/service/auth.service.ts
  server/src/domain/history/history.module.ts
  server/src/domain/history/repository/history.repository.ts
  server/src/domain/history/service/history.service.ts
  server/src/domain/user/controller/user.controller.ts
  server/src/domain/user/service/user.service.ts
  server/src/domain/user/user.entity.ts
  server/src/domain/user/user.module.ts
  server/src/scheduler/scheduler.module.ts
  server/src/scheduler/scheduler.service.ts
Labels: 🎯 백엔드, 🔑 로그인, 📄 사용자 정보

#181 디자인 추가, Fetch 함수 개선
  client/package.json
  client/src/components/Button.tsx
  client/src/components/LoginForm.tsx
  client/src/components/Modal.tsx
  client/src/components/RoomBox.tsx
  client/src/components/Select.tsx
  client/src/components/main/CreateForm.tsx
  client/src/components/room/tadaktadak/VideoController.tsx
  client/src/pages/Main/Main.tsx
  client/src/styles/GlobalStyles.ts
  client/src/styles/styled.d.ts
  client/src/styles/theme.ts
  client/src/utils/apiUtils.ts
  client/src/utils/apis.ts
  client/src/utils/cookie.ts
  client/src/utils/utils.ts
  client/tsconfig.json
Labels: 🎯 프론트엔드, 📄 메인

#184 프로젝트 스타일 변경
  client/src/components/Button.tsx
  client/src/components/JoinForm.tsx
  client/src/components/LoginForm.tsx
  client/src/components/Modal.tsx
  client/src/components/RoomBox.tsx
  client/src/components/Select.tsx
  client/src/components/main/CreateForm.tsx
  client/src/components/main/SideBar.tsx
  client/src/styles/GlobalStyles.ts
  client/src/styles/styled.d.ts
  client/src/styles/theme.ts
Labels: 🎯 프론트엔드

#185 소개 페이지 모닥불 인터랙션 및 메인 페이지 CSS 작업
  client/public/index.html
  client/src/components/FireAnimation/index.tsx
  client/src/components/FireAnimation/style.css
  client/src/components/InfoMessage.tsx
  client/src/components/JoinForm.tsx
  client/src/components/LoginForm.tsx
  client/src/components/Modal.tsx
  client/src/components/RoomBox.tsx
  client/src/components/Select.tsx
  client/src/components/main/CreateForm.tsx
  client/src/components/main/SideBar.tsx
  client/src/pages/Introduction/Introduction.tsx
  client/src/styles/GlobalStyles.ts
  client/src/styles/styled.d.ts
  client/src/styles/theme.ts
Labels: 🎯 프론트엔드, 📄 소개, 📄 메인

#187 s3 sdk 오류 해결 (이어서) 디폴트 이미지 로딩 (이어서) 방 접속 인원 소켓 (마침 다음 글)
  server/api/src/builder/index.ts
  server/api/src/builder/visit.builder.ts
  server/api/src/domain/auth/auth.repository.ts
  server/api/src/domain/auth/service/auth.service.ts
  server/api/src/domain/history/controller/history.controller.ts
  server/api/src/domain/history/history.module.ts
  server/api/src/domain/history/repository/visit.repository.ts
  server/api/src/domain/history/service/history.service.ts
  server/api/src/domain/history/visit.entity.ts
  server/api/src/domain/image/service/image.service.ts
  server/api/src/domain/user/service/user.service.ts
  server/api/src/domain/user/user.entity.ts
  server/api/src/scheduler/scheduler.module.ts
  server/api/src/scheduler/scheduler.service.ts
  server/socket/src/app.gateway.ts
Labels: 🎯 백엔드, 📄 사용자 정보, 📄 룸 사이드바

#188 소켓 서버 연동 및 인프라 작업
  .gitignore
  script/install_docker.sh
  script/install_nodejs.sh
  script/setting_all.sh
  server/socket/package.json
  server/socket/src/app.gateway.ts
  server/socket/src/main.ts
Labels: 🎯 백엔드, 🔴 Must, 📄 캠프파이어, 📄 타닥타닥, 📄 코딩 라이브, 🛒 데브옵스

#186 방 사이드바 관련 작업, 소켓 생성 및 리팩토링 수행
  client/package-lock.json
  client/package.json
  client/src/components/FireAnimation/index.tsx
  client/src/components/InfoMessage.tsx
  client/src/components/JoinForm.tsx
  client/src/components/LoginForm.tsx
  client/src/components/LoginModal.tsx
  client/src/components/VideoBox.tsx
  client/src/components/common/Button.tsx
  client/src/components/common/Modal.tsx
  client/src/components/common/Select.tsx
  client/src/components/common/Tab.tsx
  client/src/components/main/CreateForm.tsx
  client/src/components/main/SideBar.tsx
  client/src/components/room/tadaktadak/ChatList.tsx
  client/src/components/room/tadaktadak/ParticipantList.tsx
  client/src/components/room/tadaktadak/RoomSideBar.tsx
  client/src/components/room/tadaktadak/ScreenShareDiv.tsx
  client/src/components/room/tadaktadak/VideoController.tsx
  client/src/components/room/tadaktadak/Videos.tsx
  client/src/hooks/useInput.tsx
  client/src/pages/Room/Room.tsx
  client/src/pages/Room/style.ts
  client/src/socket.ts
  client/src/styles/styled.d.ts
  client/src/styles/theme.ts
  client/src/utils/apis.ts
  client/yarn.lock
Labels: 🎯 프론트엔드, 📄 룸 사이드바

#190 소켓 참가자와 채팅 목록 연동, 방 사이드바에 적용
  client/craco.config.js
  client/src/components/room/tadaktadak/ChatList.tsx
  client/src/components/room/tadaktadak/ParticipantList.tsx
  client/src/components/room/tadaktadak/RoomSideBar.tsx
  client/src/components/room/tadaktadak/VideoController.tsx
  client/src/contexts/userContext.tsx
  client/src/pages/Main/Main.tsx
  client/src/pages/Room/Room.tsx
  client/src/utils/apiUtils.ts
  client/src/utils/apis.ts
  client/tsconfig.paths.json
Labels: 🎯 프론트엔드, 📄 룸 사이드바, 📄 타닥타닥

#192 메시지 전송 로직 & 추방 기능 & API 서버 리펙토링
  server/api/src/builder/index.ts
  server/api/src/builder/room/room.builder.ts
  server/api/src/builder/user/user-response.dto.builder.ts
  server/api/src/builder/user/user.builder.ts
  server/api/src/domain/room/controller/room.controller.ts
  server/api/src/domain/room/dto/create-room-response.dto.ts
  server/api/src/domain/room/dto/room-response.dto.ts
  server/api/src/domain/room/repository/room.repository.ts
  server/api/src/domain/room/service/room.service.ts
  server/api/src/domain/user/dto/user-response.dto.ts
  server/socket/package-lock.json
  server/socket/package.json
  server/socket/src/app.gateway.ts
  server/socket/src/app.module.ts
  server/socket/src/gateway/room.gateway.spec.ts
  server/socket/src/gateway/room.gateway.ts
  server/socket/src/gateway/room.interface.ts
  server/socket/tsconfig.json
Labels: 🎯 백엔드, 🔴 Must, 📄 캠프파이어, 📄 타닥타닥, 📄 코딩 라이브

#189 방 타입 선택하는 탭 구현 및 기타 CSS 작업
  client/src/components/InfoMessage.tsx
  client/src/components/JoinForm.tsx
  client/src/components/RoomBox.tsx
  client/src/components/common/Select.tsx
  client/src/components/common/Tab.tsx
  client/src/components/fireAnimation/index.tsx
  client/src/components/fireAnimation/style.css
  client/src/components/main/RoomList.tsx
  client/src/components/main/ServiceInfo.tsx
  client/src/components/main/SideBar.tsx
  client/src/pages/Introduction/Introduction.tsx
  client/src/pages/Main/Main.tsx
  client/src/pages/Main/style.ts
  client/src/pages/Room/Room.tsx
  client/src/styles/styled.d.ts
  client/src/styles/theme.ts
  client/src/utils/apis.ts
  client/tsconfig.json
  client/yarn.lock
Labels: 🎯 프론트엔드, 📄 메인

#191 auth와 user repository 합치기 / 어제 방문 수 조회 API 에러 고치기 / 개발 분야 리스트 조회 API 추가
  server/api/src/app.module.ts
  server/api/src/builder/user/user.builder.ts
  server/api/src/domain/auth/auth.module.ts
  server/api/src/domain/auth/auth.repository.ts
  server/api/src/domain/auth/controller/auth.controller.ts
  server/api/src/domain/auth/dto/user-response.dto.ts
  server/api/src/domain/auth/service/auth.service.ts
  server/api/src/domain/field/controller/dev-field.controller.ts
  server/api/src/domain/field/dev-field.entity.ts
  server/api/src/domain/field/dev-field.module.ts
  server/api/src/domain/field/repository/dev-field.repository.ts
  server/api/src/domain/history/history.module.ts
  server/api/src/domain/history/repository/visit.repository.ts
  server/api/src/domain/history/service/history.service.ts
  server/api/src/domain/user/repository/user.repository.ts
  server/api/src/domain/user/service/user.service.ts
  server/api/src/domain/user/user.entity.ts
  server/api/src/domain/user/user.module.ts
  server/api/src/scheduler/scheduler.module.ts
  server/api/src/scheduler/scheduler.service.ts
Labels: 🎯 백엔드, 📄 메인

#198 회원 가입 시 개발 분야 저장 / 방 정보 관리 구조 약간 수정 / 방 인원 체크 소켓 이벤트 추가
  server/api/src/domain/auth/auth.module.ts
  server/api/src/domain/auth/service/auth.service.ts
  server/socket/src/gateway/room.gateway.ts
  server/socket/src/gateway/room.interface.ts
Labels: 🎯 백엔드, 📄 캠프파이어, 📄 타닥타닥

#202 Hotfix: 채팅 멈추는 현상 수정 및 최적화
  client/src/components/room/tadaktadak/Chat.tsx
  client/src/components/room/tadaktadak/ChatList.tsx
  client/src/utils/apiUtils.ts
Labels: 🎯 프론트엔드

#204 devFieldId -> devField로 수정
  server/api/src/domain/auth/dto/join-request.dto.ts
  server/api/src/domain/auth/service/auth.service.ts
  server/api/src/domain/auth/strategy/jwt.strategy.ts
Labels: 🎯 백엔드

#209 암호화 키 추가
  server/api/src/domain/auth/auth.module.ts
Labels: 🎯 백엔드

#210 방 기능 설정/ 방 입장 로직 변경 / 개발분야 컨텍스트, 태그 추가
  client/src/apis.ts
  client/src/components/JoinForm.tsx
  client/src/components/RoomBox.tsx
  client/src/components/VideoBox.tsx
  client/src/components/main/SideBar.tsx
  client/src/components/room/tadaktadak/ParticipantList.tsx
  client/src/components/room/tadaktadak/RoomSideBar.tsx
  client/src/contexts/devFieldContext.tsx
  client/src/contexts/userContext.tsx
  client/src/pages/Main/Main.tsx
  client/src/styles/styled.d.ts
  client/src/styles/theme.ts
Labels: 🎯 프론트엔드, 📄 룸 사이드바, 📄 메인

#211 회원 정보 페이지 스켈레톤
  client/src/App.tsx
  client/src/apis.ts
  client/src/components/main/SideBar.tsx
  client/src/components/profile/InfoForm.tsx
  client/src/components/profile/ModifyForm.tsx
  client/src/components/profile/UserInfo.tsx
  client/src/pages/Profile/Profile.tsx
  client/src/pages/Profile/index.ts
  client/src/pages/Profile/style.ts
  client/src/utils/apiUtils.ts
  server/api/src/domain/field/controller/dev-field.controller.ts
  server/api/src/domain/history/service/history.service.ts
  server/api/src/domain/user/controller/user.controller.ts
  server/api/src/domain/user/dto/user-update.dto.ts
  server/api/src/domain/user/service/user.service.ts
Labels: 🎯 프론트엔드, 🎯 백엔드, 📄 사용자 정보

#212 nickname 통일
  server/api/src/builder/user/user-response.dto.builder.ts
  server/api/src/builder/user/user.builder.ts
  server/api/src/domain/auth/dto/user-response.dto.ts
  server/api/src/domain/auth/service/auth.service.ts
  server/api/src/domain/room/dto/room-response.dto.ts
  server/api/src/domain/user/dto/user-response.dto.ts
  server/api/src/domain/user/user.entity.ts
Labels: 🎯 백엔드

#219 Redis Pub/Sub 연결 & Redis Remote Storage 연결 및 대응 & Socket Server CI/CD & Dockerfile
  .github/workflows/BE-Socket-Server-CI&CD.yml
  .github/workflows/BE-Socket-Server-CI.yml
  script/README.md
  script/install_docker.sh
  script/install_nodejs.sh
  script/setting_all.sh
  server/api/Dockerfile
  server/socket/Dockerfile
  server/socket/package.json
Labels: 🎯 백엔드, 🔴 Must, 📄 캠프파이어, 📄 타닥타닥, 🛒 데브옵스

#218 아바타 삭제 / 오류 수정
  client/src/apis.ts
  client/src/components/profile/InfoForm.tsx
  client/src/components/profile/ModifyForm.tsx
  client/src/components/profile/UserInfo.tsx
  client/src/pages/Profile/Profile.tsx
  client/src/utils/apiUtils.ts
  server/api/src/builder/user/user.builder.ts
  server/api/src/domain/auth/service/auth.service.ts
  server/api/src/domain/history/repository/history.repository.ts
  server/api/src/domain/history/repository/visit.repository.ts
  server/api/src/domain/history/service/history.service.ts
  server/api/src/domain/room/room.entity.ts
  server/api/src/domain/user/controller/user.controller.ts
  server/api/src/domain/user/follow.entity.ts
  server/api/src/domain/user/repository/user.repository.ts
  server/api/src/domain/user/service/user.service.ts
  server/api/src/domain/user/user.entity.ts
Labels: 🎯 프론트엔드, 🎯 백엔드, 📄 사용자 정보

#214 방 검색 기능 추가
  client/package-lock.json
  client/package.json
  client/src/components/common/Loader.tsx
  client/src/components/main/RoomList.tsx
  client/src/components/main/SearchBar.tsx
  client/src/utils/apiUtils.ts
  client/yarn.lock
Labels: 🎯 프론트엔드, 📄 메인

#224 버그 수정, 통일성을 위한 작업 수행
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/apis.ts
  client/src/components/RoomBox.tsx
  client/src/components/main/SideBar.tsx
  client/src/components/profile/UserInfo.tsx
  client/src/components/room/campfire/CampfireController.tsx
  client/src/components/room/tadaktadak/ChatList.tsx
  client/src/components/room/tadaktadak/ParticipantList.tsx
  client/src/components/room/tadaktadak/RoomSideBar.tsx
  client/src/components/room/tadaktadak/VideoController.tsx
  client/src/pages/Campfire/Campfire.tsx
  client/src/pages/Main/Main.tsx
  client/src/pages/Room/index.ts
  client/src/pages/Tadak/Tadak.tsx
  client/src/pages/Tadak/index.ts
  client/src/pages/Tadak/style.ts
  client/src/socket/socket.ts
  client/src/socket/socketEvents.ts
  client/tsconfig.paths.json
  client/yarn.lock
Labels: 🎯 프론트엔드

#225 검색 기능 수정 및 무한 스크롤 구현 중
  client/src/components/JoinForm.tsx
  client/src/components/LoginForm.tsx
  client/src/components/LoginModal.tsx
  client/src/components/RoomBox.tsx
  client/src/components/VideoBox.tsx
  client/src/components/common/Modal.tsx
  client/src/components/main/CreateForm.tsx
  client/src/components/main/RoomList.tsx
  client/src/components/main/SearchBar.tsx
  client/src/components/main/SideBar.tsx
  client/src/components/room/campfire/CamperAvatar.tsx
  client/src/components/room/tadaktadak/ChatList.tsx
  client/src/components/room/tadaktadak/RoomSideBar.tsx
  client/src/hooks/useDebounce.ts
  client/src/hooks/useInput.ts
  client/src/hooks/useIntersectionObserver.ts
  client/src/utils/constant.ts
Labels: 🎯 프론트엔드, 📄 메인

#227 API 서버 CI&CD script
  .github/workflows/BE-API-Server-CI&CD.yml
Labels: 🎯 백엔드, 🛒 데브옵스

#226 무한 스크롤 구현
  client/src/components/main/RoomList.tsx
  client/src/components/main/SideBar.tsx
  client/src/pages/Main/Main.tsx
  client/src/utils/constant.ts
Labels: 🎯 프론트엔드, 📄 메인

#228 통일성 부여 및 디자인 작업
  client/src/components/JoinForm.tsx
  client/src/components/LoginForm.tsx
  client/src/components/LoginModal.tsx
  client/src/components/RoomBox.tsx
  client/src/components/VideoBox.tsx
  client/src/components/common/Form.tsx
  client/src/components/common/Modal.tsx
  client/src/components/common/SideBar.tsx
  client/src/components/main/CreateForm.tsx
  client/src/components/main/MainSideBar.tsx
  client/src/components/main/RoomList.tsx
  client/src/components/main/SearchBar.tsx
  client/src/components/profile/InfoForm.tsx
  client/src/components/room/campfire/CamperAvatar.tsx
  client/src/components/room/tadaktadak/ChatList.tsx
  client/src/components/room/tadaktadak/ParticipantList.tsx
  client/src/components/room/tadaktadak/RoomSideBar.tsx
  client/src/components/room/tadaktadak/VideoController.tsx
  client/src/contexts/themeContext.tsx
  client/src/pages/Main/Main.tsx
  client/src/pages/Profile/Profile.tsx
  client/src/styles/GlobalStyles.ts
  client/src/utils/constant.ts
  client/src/utils/styleConstant.ts
Labels: 🎯 프론트엔드

#230 방 리스트 조회 데이터 정리(Owner 정보 추가)
  server/api/src/domain/room/controller/room.controller.ts
  server/api/src/domain/room/repository/room.repository.ts
  server/api/src/domain/room/service/room.service.ts
  server/socket/tsconfig.json
Labels: 🎯 백엔드, 🔴 Must, 📄 메인

#232 툴팁 프론트엔드 작업과 소켓 방 제거 이벤트를 개선
  client/src/components/common/Tab.tsx
  client/src/components/main/QuestionButton.tsx
  client/src/components/main/RoomList.tsx
  client/src/utils/constant.ts
  server/api/src/builder/user/user-response.dto.builder.ts
  server/api/src/domain/room/dto/room-response.dto.ts
  server/api/src/domain/user/dto/user-response.dto.ts
  server/socket/src/gateway/room.gateway.ts
Labels: 🎯 프론트엔드, 🎯 백엔드, 🔴 Must, 📄 캠프파이어, 📄 메인, 📄 코딩 라이브

#234 잔디 조회 API
  server/api/src/domain/history/dto/history-response.dto.ts
  server/api/src/domain/history/repository/history.repository.ts
  server/api/src/domain/history/service/history.service.ts
  server/api/src/domain/user/controller/user.controller.ts
Labels: 🎯 백엔드, 📄 사용자 정보

#242 토스트 메세지 구현
  client/src/App.tsx
  client/src/components/InfoMessage.tsx
  client/src/components/JoinForm.tsx
  client/src/components/LoginForm.tsx
  client/src/components/largeFireAnimation/index.tsx
  client/src/components/largeFireAnimation/style.css
  client/src/components/room/campfire/CamperList.tsx
  client/src/components/room/tadaktadak/Videos.tsx
  client/src/components/toast/Toast.tsx
  client/src/components/toast/ToastContainer.tsx
  client/src/contexts/ToastContext.tsx
  client/src/hooks/useToast.ts
  client/src/index.tsx
  client/src/pages/Campfire/Campfire.tsx
  client/src/pages/Tadak/Tadak.tsx
  client/src/utils/constant.ts
  client/src/utils/styleConstant.ts
Labels: 🎯 프론트엔드

#258 Redis Pub/Sub & Room 검색 API 수정 & 방 버그 관련 작업 & 소켓 서버 리펙토링
  .github/workflows/BE-API-Server-CI&CD.yml
  .github/workflows/BE-Socket-Server-CI&CD.yml
  server/api/src/domain/room/controller/room.controller.ts
  server/api/src/domain/room/repository/room.repository.ts
  server/api/src/domain/room/service/room.service.ts
  server/socket/package-lock.json
  server/socket/package.json
  server/socket/src/app.module.ts
  server/socket/src/config/cors.config.ts
  server/socket/src/constant/url.constant.ts
  server/socket/src/exception/client.exception.ts
  server/socket/src/exception/room.exception.ts
  server/socket/src/filter/ws-exception.filter.ts
  server/socket/src/gateway/room.gateway.ts
  server/socket/src/gateway/room.module.ts
  server/socket/src/gateway/room.service.ts
  server/socket/src/main.ts
Labels: 🎯 백엔드, 📄 캠프파이어, 📄 타닥타닥

#254 토스트 추가, 마이페이지 사진 업로드 수정, 아고라 소켓 활성화 순서 정의
  client/package-lock.json
  client/package.json
  client/src/apis.ts
  client/src/components/JoinForm.tsx
  client/src/components/LoginForm.tsx
  client/src/components/RoomBox.tsx
  client/src/components/common/Loader.tsx
  client/src/components/main/CreateForm.tsx
  client/src/components/main/MainSideBar.tsx
  client/src/components/room/tadaktadak/RoomSideBar.tsx
  client/src/hooks/useToast.ts
  client/src/pages/Campfire/Campfire.tsx
  client/src/pages/Tadak/Tadak.tsx
  client/src/utils/apiUtils.ts
  client/src/utils/constant.ts
  client/src/utils/styleConstant.ts
  client/src/utils/utils.ts
  client/yarn.lock
Labels: 🎯 프론트엔드, 버그

#260 버그 수정, any 타입 제거
  client/src/apis.ts
  client/src/components/JoinForm.tsx
  client/src/components/LoginForm.tsx
  client/src/components/RoomBox.tsx
  client/src/components/main/CreateForm.tsx
  client/src/components/main/MainSideBar.tsx
  client/src/components/profile/ModifyForm.tsx
  client/src/components/profile/UserInfo.tsx
  client/src/components/room/tadaktadak/RoomSideBar.tsx
  client/src/pages/Campfire/Campfire.tsx
  client/src/utils/constant.ts
  client/src/utils/utils.ts
  server/api/src/domain/history/controller/history.controller.ts
Labels: 버그

#264 프로젝트 구조, 변수, 의존성 리팩토링
  client/src/components/chat/ChatCard/index.tsx
  client/src/components/chat/ChatCard/style.ts
  client/src/components/chat/ChatList/index.tsx
  client/src/components/chat/ChatList/style.ts
  client/src/components/common/CircleButton/index.tsx
  client/src/components/common/CircleButton/style.ts
  client/src/components/common/SideBar.tsx
  client/src/components/form/Form/index.tsx
  client/src/components/form/Form/style.ts
  client/src/components/form/Join/index.tsx
  client/src/components/form/Join/style.ts
  client/src/components/form/Login/index.tsx
  client/src/components/form/Login/style.ts
  client/src/components/form/MakeRoom/index.tsx
  client/src/components/form/MakeRoom/style.ts
  client/src/components/main/MainSideBar.tsx
  client/src/components/modal/Login/index.tsx
  client/src/components/modal/Modal/index.tsx
  client/src/components/modal/Modal/style.ts
  client/src/components/profile/Avatar/index.tsx
  client/src/components/profile/Avatar/style.ts
  client/src/components/profile/GrassArea/index.tsx
  client/src/components/profile/GrassArea/style.ts
  client/src/components/profile/InfoCard/index.tsx
  client/src/components/profile/InfoCard/style.ts
  client/src/components/profile/InfoForm.tsx
  client/src/components/profile/ModifyForm.tsx
  client/src/components/profile/ModifyInfoCard/index.tsx
  client/src/components/profile/ModifyInfoCard/style.ts
  client/src/components/profile/PageContainer/index.tsx
  client/src/components/profile/PageContainer/style.ts
  client/src/components/profile/UserInfo.tsx
  client/src/components/room/campfire/CampfireController.tsx
  client/src/components/room/tadaktadak/VideoController.tsx
  client/src/components/sideBar/Main/index.tsx
  client/src/components/sideBar/Main/style.ts
  client/src/components/sideBar/Room/index.tsx
  client/src/components/sideBar/Room/style.ts
  client/src/components/sideBar/SideBar/index.tsx
  client/src/components/sideBar/SideBar/style.ts
  client/src/contexts/userContext.tsx
  client/src/pages/Campfire/Campfire.tsx
  client/src/pages/Main/Main.tsx
  client/src/pages/Profile/Profile.tsx
  client/src/pages/Tadak/Tadak.tsx
  client/src/utils/constant.ts
  client/src/utils/styleConstant.ts
Labels: 🎯 프론트엔드, 리팩토링

#265 Auth / Room 기본 테스트코드 작성 & API 서버 코드 리펙토링
  server/api/package-lock.json
  server/api/package.json
  server/api/src/builder/auth/join-request.dto.builder.ts
  server/api/src/builder/dev-field.builder.ts
  server/api/src/builder/user/user.builder.ts
  server/api/src/domain/auth/controller/auth.controller.spec.ts
  server/api/src/domain/auth/dto/join-request.dto.ts
  server/api/src/domain/auth/service/auth.service.spec.ts
  server/api/src/domain/auth/service/auth.service.ts
  server/api/src/domain/room/controller/room.controller.spec.ts
  server/api/src/domain/room/controller/room.controller.ts
  server/api/src/domain/room/service/room.service.spec.ts
  server/api/src/domain/room/service/room.service.ts
  server/api/src/domain/user/controller/user.controller.spec.ts
  server/api/src/domain/user/service/user.service.spec.ts
Labels: 🎯 백엔드

#267 정상 User, Room, DevField Mock 객체 생성 작업 & 방 퇴장, 입장, uuid로 단일 방 정보 조회 테스트 코드
  server/api/src/domain/auth/service/auth.service.spec.ts
  server/api/src/domain/room/service/room.service.spec.ts
  server/api/src/domain/room/service/room.service.ts
  server/api/test/mock.object.ts
Labels: 🎯 백엔드

#268 프로필 페이지 레이아웃 조정, 개발필드 활성화, type 정리, api 디렉토리 생성 및 정리
  client/src/apis/apiUtils.ts
  client/src/apis/fetchFns.ts
  client/src/apis/fetcher.ts
  client/src/apis/index.ts
  client/src/apis/options.ts
  client/src/components/ServiceInfo/style.ts
  client/src/components/form/Login/index.tsx
  client/src/components/form/Login/style.ts
  client/src/components/profile/Avatar/index.tsx
  client/src/components/profile/Avatar/style.ts
  client/src/components/profile/GrassArea/index.tsx
  client/src/components/profile/GrassArea/style.ts
  client/src/components/profile/InfoCard/style.ts
  client/src/components/profile/ModifyInfoCard/style.ts
  client/src/components/profile/PageContainer/index.tsx
  client/src/components/profile/PageContainer/style.ts
  client/src/components/room/RoomCard/index.tsx
  client/src/components/room/RoomCard/style.ts
  client/src/components/room/RoomList/index.tsx
  client/src/components/sideBar/Main/style.ts
  client/src/components/sideBar/ParticipantList/index.tsx
  client/src/contexts/devFieldContext.tsx
  client/src/contexts/userContext.tsx
  client/src/pages/Campfire/Campfire.tsx
  client/src/pages/Introduction/Introduction.tsx
  client/src/pages/Tadak/Tadak.tsx
  client/src/styles/styled.d.ts
  client/src/styles/theme.ts
  client/src/types/devField.ts
  client/src/types/httpResponse.ts
  client/src/types/index.ts
  client/src/types/roomInfo.ts
  client/src/types/tabState.ts
  client/src/types/userInfo.ts
  client/src/utils/apiUtils.ts
  client/src/utils/constant.ts
  client/src/utils/styleConstant.ts
Labels: 🎯 프론트엔드, 리팩토링

#266 프론트 코드 구조 개선 및 토스트 메세지 디자인 버그 수정
  client/src/components/form/Join/index.tsx
  client/src/components/form/Login/index.tsx
  client/src/components/form/MakeRoom/index.tsx
  client/src/components/profile/Avatar/index.tsx
  client/src/components/profile/ModifyInfoCard/index.tsx
  client/src/components/profile/PageContainer/index.tsx
  client/src/components/room/RoomCard/index.tsx
  client/src/components/room/RoomList/index.tsx
  client/src/components/sideBar/Room/index.tsx
  client/src/components/toast/Toast/index.tsx
  client/src/components/toast/Toast/style.ts
  client/src/utils/constant.ts
  client/src/utils/styleConstant.ts
Labels: 버그, 리팩토링
